default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: CHANGEME_development

test:
  <<: *default
  database: CHANGEME_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
