test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
  service: S3
  access_key_id: <%= ENV['AWS_S3_KEY'] %>
  secret_access_key: <%=  ENV['AWS_S3_SECRET'] %>
  region: <%=  ENV['AWS_REGION'] %>
  bucket: <%=  ENV['AWS_S3_BUCKET'] %>
